
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/1.2.0/hurl_1.2.0_amd64.deb && sudo dpkg -i hurl_1.2.0_amd64.deb
      - name: Run
        run: |
          hurl --version
